### ISSUE TITLE
ちまき伝説 - 原文タイトルの誤植

### ISSUE THREAD

**Issue by minglaitin** [hanamegane/z-o_trans#26]
「傅」じゃなくて「傳」のほうが正しい字です。

新しいブランチを作成すべきかfeature/timaki_legendで直すべきかやり方がわからなくて、とにかくissueを作成しておきます。すみませんm(_ _)m

**Comment by hanamegane** [comment]
報告ありがとうございます！
誤植や既存翻訳の改良は新しいブランチで作業するつもりです。

**Comment by hanamegane** [comment]
今回の場合は
issue作成 -> developからブランチ作成 (e.g feature/#26 ,feature/#26_timaki_typo) -> 修正してプルリクエスト
といった流れになります。

**Comment by hanamegane** [comment]
feature/#26_timaki_typo

PR #27

**Comment by minglaitin** [comment]
なるほど、わかりました。
解説ありがとうございます！
