### ISSUE TITLE
採藥人 雪莉 - いくつのセリフの翻訳提案

### ISSUE THREAD

**Issue by minglaitin** [hanamegane/z-o_trans#71]
巴倫「不然我的斧子可不是放著好看的」
バロン「じゃなきゃ俺様の斧はただの見せ物じゃねえぞ」か「じゃなきゃ俺様の斧はただの飾りじゃねえぞ」

放著好看：見せるためにそこに置いてある。使う気はない。
つまり「出てこなければ攻撃するよ」みたいな感じ
___
諾曼「那個不是惡夢曼陀羅來的嗎？ 」
ノーマン「あれは悪夢マンドラじゃなかったのか？」

ヘリド達はある植物を悪夢マンドラだと思って追ってきた
そしてシェリーは「あなた達は人形草を追って樹海に来たの？」と聞きました
だからノーマンは「あれは悪夢マンドラじゃないの？」とあの植物の正体を確認したい
___
あとは翻訳の提案じゃないけど、最後のヘロイスのセリフにシェリーがシャーリーになった

**Comment by hanamegane** [comment]
ありがとうございます！
バロンのやつは自分でもよく分からない表現だなと思っていたので助かります。

ノーマンの方は直後にヘリドの台詞が続くのであれば自然ですが、シェリーのセリフなので
「あれは悪夢マンドラじゃなかったのか？」が正しいですね。

雪莉って見るとどうもこいつが頭をよぎってシャーリーになっちゃうんです。許してください。
![prtsc](https://pbs.twimg.com/media/DgMvv8sV4AAEHCE?format=jpg&name=small)
