### ISSUE TITLE
放狠話時請注意 - 誤字と翻訳の提案

### ISSUE THREAD

**Issue by minglaitin** [hanamegane/z-o_trans#85]
諾曼「怎麼我的**廣**法都不管用了」
**魔**法です
___
バロンは「わんこは黙ってろ」とか言って、ノーマンは「誰がわんこだ！お前がわんこだろ！お前の家族全員わんこだ！」だったらどうでしょうか？

**Comment by hanamegane** [comment]
`魔法です`
Thx!

`バロンは「わんこは黙ってろ」とか言って、ノーマンは「誰がわんこだ！お前がわんこだろ！お前の家族全員わんこだ！」だったらどうでしょうか？`
原文をそのまま訳すとその通りになると思いますが、唐突に「バロンは犬」と言われても、何のことだかわからないぞ？となると思います。

「你才XXX，你全家都XXX」という言い回しのようですので、これをそのまま訳すのではなく、
この言い回しが指す意味や用法だけを残して自由に訳してよいと思います。

頭おかしいふりをしつつ怒る(で合っていますか？)用法を残ししつつ犬と併せて犬のうんこ書きましたが、
訳としてうんこなのでうんこじゃなくて別の案があれば良いです。

**Comment by minglaitin** [comment]
なるほど
「誰がバカだ！お前のほうがバカだろ！」に似てると思って、そのまま直訳しても通じるかなと思ったけど、そうじゃないみたいですね
ニュアンスを別の言語で伝わるの難しいですね
